<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LT012489" name="testscripts.Scenario1" tests="3" failures="0" timestamp="8 Feb 2013 10:38:22 GMT" time="65.054" errors="1">
  <testcase name="runTC3" time="33.976" classname="testscripts.Scenario1">
    <error type="java.lang.AssertionError" message="Login failed for valid user">
      <![CDATA[java.lang.AssertionError: Login failed for valid user
	at org.testng.Assert.fail(Assert.java:94)
	at supportlibraries.DriverScript.wrapUp(DriverScript.java:515)
	at supportlibraries.DriverScript.driveTestExecution(DriverScript.java:88)
	at testscripts.Scenario1.runTC3(Scenario1.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:128)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- runTC3 -->
  <testcase name="runTC1" time="11.603" classname="testscripts.Scenario1"/>
  <testcase name="runTC2" time="19.475" classname="testscripts.Scenario1"/>
</testsuite> <!-- testscripts.Scenario1 -->
